[package]
name = "logid"
version = "0.7.1"
edition = "2021"
description = "Rust logging framework using IDs to identify log entries."
repository = "https://github.com/mhatzl/logid"
license = "MIT"
keywords = ["logging", "tracing"]
categories = ["development-tools::debugging"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.35"
once_cell = "1.13.0"
chrono = "0.4.22"
dashmap = "5.4.0"

[features]
diagnostics = []
causes = []

[dev-dependencies]
tracing-subscriber = "0.3.15"
