name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all-features
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      # Sequential testing required since all log entries are stored in one central hashmap
      run: cargo test --verbose --all-features -- --test-threads 1
      
  lint:
    name: Run Linter (clippy)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      run: cargo clippy --all-features -- -D warnings

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo fmt
      run: cargo fmt -- --check
